lightoj-dev/problem-tutorials

1015/en.md

Add tutorial for LOJ-1015 : Brush (I)

---

1015/bn.md

Add Bangla tutorial for LOJ - 1015 : Brush (I)

---

1225/en.md

Add English tutorial for LOJ - 1225 : Palindromic Numbers (II)

---

1029/en.md

Loj 1029 - Civil and Evil Engineer

---

1182/en.md

Add English tutorial for LOJ 1182

---

1129/en.md

Editorial on 1129 - Consistency Checker problem on lightoj.
It is a Trie based problem. Check!

1129 - Consistency Checker (#33 assigned)

---

1338/en.md

Added English tutorial for LOJ - 1338 : Hidden Secret!

---

1286/en.md

Add tutorial for LOJ-1286 Space Shuttle Experiments

---

1059/en.md

Resolves: https://github.com/lightoj-dev/problem-tutorials/issues/66

Added English tutorial for LOJ-1059: Air Ports

---

1088/en.md

I have added an English tutorial for LOJ 1088.

Adding en.md for 1088 to new_branch

---

1258/en.md

Minor markdown and grammar changes

---

1047/en.md

eng. tut added

---

1387/en.md

Add English tutorial for LOJ 1387 - Setu

---

1102/en.md

Fixed markdown, spacing, wording in 1102/en

---

1053/en.md

Add English tutorial for LOJ 1053 - Higher Math

---

1006/en.md

I would really appreciate if there is any other suggestion to improve this.

Add English editorial for LightOJ 1006

---

1148/en.md

Let me know if you need any changes.

Add tutorial LOJ 1148 - Mad Counting en.md

---

1109/en.md

Add English tutorial for LOJ 1109 - False Ordering

---

1179/en.md

Have a look and let me know if you need any changes

Add Tutorial for LOJ 1179- Josephus Problem

---

1078/en.md

Add tutorial for 1078 - Integer Divisibility

---

1049/en.md

Added the English tutorial of Loj 1049 (One Way Roads) Problem

---

1020/en.md

Add English Tutorial for LOJ 1020- A Childhood Game

---

1147/en.md

Add English Tutorial for LOJ 1147 - Tug of War

---

1289/en.md

Add editorial to problem 1289 (en): Issue 196

---

1212/en.md

The commit contains the 1212 file contains the English tutorial for the problem as en.md per community guidelines. I hope this helps.

English Editorial for LOJ-1212(Double ended queue) 

---

1009/en.md
1212/en.md

Added the English tutorial for LOJ-1009 with links to resources and solution code. Please check the updates .

LOJ-1009 (Back to Underworld) Editorial in English

---

1111/en.md
1111/graph-1.svg

Added the English Editorial for LOJ-1111 . Wasn't sure about the guidelines on adding images or graphs. So , Added images directly in the folder  in a SVG format for now.

LOJ - 1111 (Best Picnic Ever) Editorial

---

1094/en.md
1094/graph-1.svg
1094/graph-2.svg

The editorial is in English . Also includes two graphs explaining the second test case for a walkthrough the problem. My solution uses BFS , it might be solvable using DFS too. I hope some one will cover  that and maybe add some explanation and illustration for first test case.

LOJ-1094 (Furthest Nodes of a Tree) English Tutorial

---

1100/en.md

Link :  https://lightoj.com/problem/again-array-queries

Added a tutorial on LOJ-1100(Again Array Queries)

---

1213/en.md

Link : https://lightoj.com/problem/fantasy-of-a-summation

Added a tutorial on LOJ-1213(Fantasy of a Summation)

---

1189/en.md

Added the English editorial for LOJ-1189 (Sum of Factorials) with code and examples.

Editorial for LOJ-1189 (Sum of Factorials)

---

1063/en.md

ISSUE: https://github.com/lightoj-dev/problem-tutorials/issues/223

Adding English Editorial for LOJ-1063

---

1021/en.md

english editorial of painful bases.

Added editorial of LOJ 1021 - Painful Bases

---

1141/en.md
1141/graph-1.svg
1189/en.md

Added the English editorial with one relevant illustration for LOJ-1141 ( Number transformation) . Sorry for the long delay this time.

LOJ-1141 : Number transformation Editorial

---

1447/en.md

Added LOJ 1447 - Shadow Sum Editorial (en)

---

1035/en.md

Added editorial for LOJ 1035 - Intelligent Factorial Factorization (en)

---

1095/en.md

Tutorial for LOJ 1095 - Arrange the Numbers (en)

---

1393/en.md

Added Tutorial for LOJ 1393 - Crazy Calendar (en)

---

1141/en.md
1141/graph-1.svg
1189/en.md
1303/en.md

Added the English tutorial with solution code in C++.

Added LOJ-1303: Ferris Wheel Editorial (English)

---

1112/en.md

Added the tutorial in English with accepted solution code in C++.

Added tutorial for LOJ-1112: Curious Robin Hood

---

1096/1096.md

Add tutorial for LOJ-1096 : nth Term

---

1249/en.md

Added a tutorial in **javascript**

Add english tutorial for loj-1249 : Chocolate thief

---

1341/en.md

Added tutorial for [LOJ-1341: Aladin and the flying carpet](https://lightoj.com/problem/aladdin-and-the-flying-carpet) in English. Links to extra resources have been added to explain some techniques like sieve for the readers.
This pull request closes the issue #366  which has been assigned to me.

Added tutorial for LOJ-1341

---

1076/en.md

Added English tutorial of Loj:1076 Get the containers.  linked of extra recourses  has been added for binary search.
This pull request is closes to issue no #368 which is assigned to me.

Tutorial for Loj 1076:Get the Containners

---

1297/en.md

Add tutorial for LOJ-1297 Largest Box

---

1338/en.md

add python solution for problem 1338

---

1109/en.md

The custom sorting tutorial link was broken added a new tutorial link.

URL Broken - LOJ 1109 - False Ordering

---

1041/en.md

Thanks @showrav-ansary  for helping me to upload it into github.

English Tutorial For LOJ-1041

---

1443/en.md

Added tutorial for LOJ-1443 (en)

---

.github/PULL_REQUEST_TEMPLATE.md

Add a PR template to make it easier for contributors to submit PRs with all the necessary information. It should be helpful for reviewers.

feat: Add Pull Request template

---

dimik-factorial/en.md

Closes #475 .
Problem link: https://lightoj.com/problem/dimik-factorial
- This PR adds an English tutorial for problem dimik factorial.
- This PR adds a new solution approach.

Adding a tutorial for dimik-factorial
